# Generated by Django 2.2.1 on 2019-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week', models.IntegerField()),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
                ('team3', models.TextField()),
                ('team4', models.TextField()),
                ('team5', models.TextField()),
            ],
        ),
    ]
